# This file is AUTO-GENERATED by codegen/generate.py
# Do not edit manually – re-run the generator instead.
#
# To regenerate:
#   python codegen/generate.py \
#       --schema codegen/schemas/market.json \
#       --output lolzteam/market/_generated.py \
#       --class MarketAPI
from __future__ import annotations

from typing import Any, Dict, List, Optional

from .._core.mixin import ApiMixin


class MarketAPI(ApiMixin):
    """Auto-generated Market API methods.

    This is a minimal stub.  Run the code-generator against the official
    market.json OpenAPI schema to populate all methods.
    """

    # ------------------------------------------------------------------ #
    # Profile                                                             #
    # ------------------------------------------------------------------ #

    def get_me(self) -> Any:
        """Get your market profile information."""
        return self._request("GET", "/me")

    # ------------------------------------------------------------------ #
    # Listings / Items                                                    #
    # ------------------------------------------------------------------ #

    def get_items(
        self,
        page: Optional[int] = None,
        limit: Optional[int] = None,
        order_by: Optional[str] = None,
        order: Optional[str] = None,
        price_min: Optional[float] = None,
        price_max: Optional[float] = None,
    ) -> Any:
        """Get a list of market items.

        Args:
            page (int): Page number.
            limit (int): Results per page (max 250).
            order_by (str): Field to sort by.
            order (str): Sort direction.
            price_min (float): Minimum price filter.
            price_max (float): Maximum price filter.
        """
        _params = {
            "page": page,
            "limit": limit,
            "order_by": order_by,
            "order": order,
            "price_min": price_min,
            "price_max": price_max,
        }
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", "/", params=_params)

    def get_item(self, item_id: int) -> Any:
        """Get a single market item.

        Args:
            item_id (int): Item ID.
        """
        _path = f"/{item_id}"
        return self._request("GET", _path, params={})

    def post_item_buy(
        self,
        item_id: int,
        price: float,
        currency: str,
        buy_without_validation: Optional[int] = None,
    ) -> Any:
        """Purchase an item.

        Args:
            item_id (int): Item ID.
            price (float): Expected price (used to guard against price changes).
            currency (str): Currency code, e.g. ``"rub"``.
            buy_without_validation (int): Skip pre-purchase validation.
        """
        _path = f"/{item_id}/buy"
        _data = {
            "price": price,
            "currency": currency,
            "buy_without_validation": buy_without_validation,
        }
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, json=_data)

    def get_item_email_password(self, item_id: int) -> Any:
        """Get the login data for a purchased item.

        Args:
            item_id (int): Item ID.
        """
        _path = f"/{item_id}/email-password"
        return self._request("GET", _path, params={})

    # ------------------------------------------------------------------ #
    # Managing                                                            #
    # ------------------------------------------------------------------ #

    def put_item_edit(
        self,
        item_id: int,
        title: Optional[str] = None,
        price: Optional[float] = None,
        currency: Optional[str] = None,
        description: Optional[str] = None,
        information: Optional[str] = None,
    ) -> Any:
        """Edit an item listing.

        Args:
            item_id (int): Item ID.
            title (str): New title.
            price (float): New price.
            currency (str): Currency code.
            description (str): New description.
            information (str): Additional information.
        """
        _path = f"/{item_id}/edit"
        _data = {
            "title": title,
            "price": price,
            "currency": currency,
            "description": description,
            "information": information,
        }
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, json=_data)

    def post_item_confirm_buy(self, item_id: int) -> Any:
        """Confirm a purchase (end warranty period).

        Args:
            item_id (int): Item ID.
        """
        _path = f"/{item_id}/confirm-buy"
        return self._request("POST", _path, json={})

    # ------------------------------------------------------------------ #
    # Payments                                                            #
    # ------------------------------------------------------------------ #

    def get_payments(
        self,
        page: Optional[int] = None,
        limit: Optional[int] = None,
        operation_type: Optional[str] = None,
    ) -> Any:
        """Get a list of payment operations.

        Args:
            page (int): Page number.
            limit (int): Results per page.
            operation_type (str): Filter by operation type.
        """
        _params = {
            "page": page,
            "limit": limit,
            "operation_type": operation_type,
        }
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", "/payments", params=_params)

    def post_transfer(
        self,
        receiver: str,
        currency: str,
        amount: float,
        comment: Optional[str] = None,
        transfer_hold: Optional[int] = None,
        hold_length_option: Optional[str] = None,
        hold_length_value: Optional[int] = None,
    ) -> Any:
        """Transfer funds to another user.

        Args:
            receiver (str): Recipient username or user ID.
            currency (str): Currency code.
            amount (float): Amount to transfer.
            comment (str): Optional comment.
            transfer_hold (int): Enable hold (1 = yes).
            hold_length_option (str): Hold length unit.
            hold_length_value (int): Hold length value.
        """
        _data = {
            "receiver": receiver,
            "currency": currency,
            "amount": amount,
            "comment": comment,
            "transfer_hold": transfer_hold,
            "hold_length_option": hold_length_option,
            "hold_length_value": hold_length_value,
        }
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", "/transfer", json=_data)
