# This file is AUTO-GENERATED by codegen/generate.py
# Do not edit manually – re-run the generator instead.
from __future__ import annotations

from typing import Any, Dict, List, Optional

from .._core.mixin import ApiMixin


class ForumAPI(ApiMixin):
    """Auto-generated API methods."""

    def o_auth_token(self) -> Any:
        """Get Access Token
        """
        _path = f"/oauth/token"
        _params = {}
        _data = {}
        return self._request("POST", _path, params=_params, json=_data)

    def assets_css(self, css: Optional[List[str]] = None) -> Any:
        """Get CSS
        
        Args:
            css (List[str]): The names or identifiers of the CSS selectors to retrieve.
        """
        _path = f"/css"
        _params = {"css": css}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def categories_list(self, parent_category_id: Optional[int] = None, parent_forum_id: Optional[int] = None, order: Optional[str] = None) -> Any:
        """Get Categories
        
        Args:
            parent_category_id (int): Id of parent category. If exists, filter categories that are direct children of that category.
            parent_forum_id (int): Id of parent forum. If exists, filter categories that are direct children of that forum.
            order (str): Ordering of categories.
        """
        _path = f"/categories"
        _params = {"parent_category_id": parent_category_id, "parent_forum_id": parent_forum_id, "order": order}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def categories_get(self, category_id: int) -> Any:
        """Get Category
        
        Args:
            category_id (int): Id of category.
        """
        _path = f"/categories/{category_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def forums_list(self, parent_category_id: Optional[int] = None, parent_forum_id: Optional[int] = None, order: Optional[str] = None) -> Any:
        """Get Forums
        
        Args:
            parent_category_id (int): Id of parent category. If exists, filter forums that are direct children of that category.
            parent_forum_id (int): Id of parent forum. If exists, filter forums that are direct children of that forum.
            order (str): Ordering of forums.
        """
        _path = f"/forums"
        _params = {"parent_category_id": parent_category_id, "parent_forum_id": parent_forum_id, "order": order}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def forums_grouped(self) -> Any:
        """Get Forums Tree
        """
        _path = f"/forums/grouped"
        _params = {}
        return self._request("GET", _path, params=_params)

    def forums_get(self, forum_id: int) -> Any:
        """Get Forum
        
        Args:
            forum_id (int): Id of forum.
        """
        _path = f"/forums/{forum_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def forums_followers(self, forum_id: int) -> Any:
        """Get Followers
        
        Args:
            forum_id (int): Id of forum.
        """
        _path = f"/forums/{forum_id}/followers"
        _params = {}
        return self._request("GET", _path, params=_params)

    def forums_follow(self, forum_id: int, post: Optional[bool] = None, alert: Optional[bool] = None, email: Optional[bool] = None, prefix_ids: Optional[List[int]] = None, minimal_contest_amount: Optional[int] = None) -> Any:
        """Follow Forum
        
        Args:
            forum_id (int): Id of forum.
            post (bool): Whether to receive notification for post.
            alert (bool): Whether to receive notification as alert.
            email (bool): Whether to receive notification as email.
            prefix_ids (List[int]): Prefix ids.
            minimal_contest_amount (int): Minimal contest amount. (Only for 766 forumId)
        """
        _path = f"/forums/{forum_id}/followers"
        _params = {}
        _data = {"post": post, "alert": alert, "email": email, "prefix_ids": prefix_ids, "minimal_contest_amount": minimal_contest_amount}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def forums_unfollow(self, forum_id: int) -> Any:
        """Unfollow Forum
        
        Args:
            forum_id (int): Id of forum.
        """
        _path = f"/forums/{forum_id}/followers"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def forums_followed(self, total: Optional[bool] = None) -> Any:
        """Get Followed Forums
        
        Args:
            total (bool): If included in the request, only the forum count is returned as **forums_total**.
        """
        _path = f"/forums/followed"
        _params = {"total": total}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def forums_get_feed_options(self) -> Any:
        """Get Feed Options
        """
        _path = f"/forums/feed/options"
        _params = {}
        return self._request("GET", _path, params=_params)

    def forums_edit_feed_options(self, node_ids: Optional[List[int]] = None, keywords: Optional[List[str]] = None) -> Any:
        """Edit Feed Options
        
        Args:
            node_ids (List[int]): Array of forum ids to exclude from the feed.
            keywords (List[str]): List of keywords to exclude specific threads from the feed.
        """
        _path = f"/forums/feed/options"
        _params = {}
        _data = {"node_ids": node_ids, "keywords": keywords}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def links_list(self) -> Any:
        """Get Links Forum
        """
        _path = f"/link-forums"
        _params = {}
        return self._request("GET", _path, params=_params)

    def links_get(self, link_id: int) -> Any:
        """Get Link Forum
        
        Args:
            link_id (int): Id of link forum.
        """
        _path = f"/link-forums/{link_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def pages_list(self, parent_page_id: Optional[int] = None, order: Optional[str] = None) -> Any:
        """Get Pages
        
        Args:
            parent_page_id (int): Id of parent page. If exists, filter pages that are direct children of that page.
            order (str): Ordering of pages.
        """
        _path = f"/pages"
        _params = {"parent_page_id": parent_page_id, "order": order}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def pages_get(self, page_id: int) -> Any:
        """Get Page
        
        Args:
            page_id (int): Id of page.
        """
        _path = f"/pages/{page_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def navigation_list(self, parent: Optional[int] = None) -> Any:
        """Get Navigation
        
        Args:
            parent (int): Id of parent element. If exists, filter elements that are direct children of that element.
        """
        _path = f"/navigation"
        _params = {"parent": parent}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def threads_list(self, forum_id: Optional[int] = None, tab: Optional[str] = None, state: Optional[str] = None, period: Optional[str] = None, title: Optional[str] = None, title_only: Optional[bool] = None, creator_user_id: Optional[int] = None, sticky: Optional[bool] = None, prefix_ids__: Optional[List[int]] = None, prefix_ids_not__: Optional[List[int]] = None, thread_tag_id: Optional[int] = None, page: Optional[int] = None, limit: Optional[int] = None, order: Optional[str] = None, direction: Optional[str] = None, thread_create_date: Optional[int] = None, thread_update_date: Optional[int] = None, fields_include: Optional[List[str]] = None) -> Any:
        """Get Threads
        
        Args:
            forum_id (int): Id of the containing forum.
            tab (str): Tab to get threads from.
            state (str): Thread state. Works only if **forum_id** is set.
            period (str): Filter to get only threads created within the selected period. Works only if **forum_id** is set.
            title (str): Thread title.
            title_only (bool): Search only in titles.
            creator_user_id (int): Filter to get only threads created by the specified user.
            sticky (bool): Filter to get only sticky or non-sticky threads. By default, all threads will be included and sticky ones will be at the top of the result on the first page. In mixed mode, sticky threads are not counted towards **threads_total** and does not affect pagination.
            prefix_ids__ (List[int]): Filter to get only threads with the specified prefix.
            prefix_ids_not__ (List[int]): Filter to get only threads without the specified prefix.
            thread_tag_id (int): Filter to get only threads with the specified tag.
            page (int): Page number of threads.
            limit (int): Number of threads in a page.
            order (str): Ordering of threads.
            direction (str): Direction of threads ordering.
            thread_create_date (int): Filter threads by creation date. Only works with 'thread_create_date' and 'thread_create_date_reverse' ordering.
            thread_update_date (int): Filter threads by update date. Only works with 'thread_update_date' and 'thread_update_date_reverse' ordering.
            fields_include (List[str]): List of fields to include.
        """
        _path = f"/threads"
        _params = {"forum_id": forum_id, "tab": tab, "state": state, "period": period, "title": title, "title_only": title_only, "creator_user_id": creator_user_id, "sticky": sticky, "prefix_ids[]": prefix_ids__, "prefix_ids_not[]": prefix_ids_not__, "thread_tag_id": thread_tag_id, "page": page, "limit": limit, "order": order, "direction": direction, "thread_create_date": thread_create_date, "thread_update_date": thread_update_date, "fields_include": fields_include}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def threads_create(self, post_body: str, forum_id: int, title: Optional[str] = None, title_en: Optional[str] = None, prefix_id: Optional[List[int]] = None, tags: Optional[List[str]] = None, hide_contacts: Optional[bool] = None, allow_ask_hidden_content: Optional[bool] = None, reply_group: Optional[int] = None, comment_ignore_group: Optional[bool] = None, dont_alert_followers: Optional[bool] = None, schedule_date: Optional[str] = None, schedule_time: Optional[str] = None, watch_thread_state: Optional[bool] = None, watch_thread: Optional[bool] = None, watch_thread_email: Optional[bool] = None) -> Any:
        """Create Thread
        
        Args:
            post_body (str): Content of the new thread.
            forum_id (int): Id of the target forum.
            title (str): Thread title. Can be skipped if **title_en** set.
            title_en (str): Thread english title. Can be skipped if **title** set.
            prefix_id (List[int]): Prefix ids.
            tags (List[str]): Thread tags.
            hide_contacts (bool): Hide contacts.
            allow_ask_hidden_content (bool): Allow ask hidden content.
            reply_group (int): Allow to reply only users with chosen or higher group.
            comment_ignore_group (bool): Allow commenting if user can't post in thread.
            dont_alert_followers (bool): Don't alert followers about thread creation.
            schedule_date (str): Date to schedule thread creation (format: `DD-MM-YYYY`).
            schedule_time (str): Time to schedule thread creation (format: `HH:MM`).
            watch_thread_state (bool): Watch thread state.
            watch_thread (bool): Receive forum notifications of new posts in this thread.
            watch_thread_email (bool): Receive email notifications of new posts in this thread.
        """
        _path = f"/threads"
        _params = {}
        _data = {"post_body": post_body, "forum_id": forum_id, "title": title, "title_en": title_en, "prefix_id": prefix_id, "tags": tags, "hide_contacts": hide_contacts, "allow_ask_hidden_content": allow_ask_hidden_content, "reply_group": reply_group, "comment_ignore_group": comment_ignore_group, "dont_alert_followers": dont_alert_followers, "schedule_date": schedule_date, "schedule_time": schedule_time, "watch_thread_state": watch_thread_state, "watch_thread": watch_thread, "watch_thread_email": watch_thread_email}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def threads_create_contest(self, post_body: str, contest_type: str, prize_type: str, require_like_count: int, require_total_like_count: int, title: Optional[str] = None, title_en: Optional[str] = None, length_value: Optional[int] = None, length_option: Optional[str] = None, count_winners: Optional[int] = None, prize_data_money: Optional[float] = None, is_money_places: Optional[bool] = None, prize_data_places: Optional[List[float]] = None, prize_data_upgrade: Optional[int] = None, secret_answer: Optional[str] = None, tags: Optional[List[str]] = None, reply_group: Optional[int] = None, comment_ignore_group: Optional[bool] = None, dont_alert_followers: Optional[bool] = None, hide_contacts: Optional[bool] = None, allow_ask_hidden_content: Optional[bool] = None, schedule_date: Optional[str] = None, schedule_time: Optional[str] = None, watch_thread_state: Optional[bool] = None, watch_thread: Optional[bool] = None, watch_thread_email: Optional[bool] = None) -> Any:
        """Create Contest
        
        Args:
            post_body (str): Content of the new contest.
            title (str): Thread title. Can be skipped if **title_en** set.
            title_en (str): Thread english title. Can be skipped if **title** set.
            contest_type (str): Contest type.
            length_value (int): Giveaway duration value. The maximum duration is 3 days. Required if **contest_type** is **by_finish_date**.
            length_option (str): Giveaway duration type. The maximum duration is 3 days. Required if **contest_type** is **by_finish_date**.
            prize_type (str): Prize type.
            count_winners (int): Winner count (prize count). Optional if **prize_type** is **money**.
            prize_data_money (float): How much money will each winner receive. Optional if **prize_type** is **money**.
            is_money_places (bool): Enable the distribution of money prizes by places. Optional if **prize_type** is **money**.
            prize_data_places (List[float]): How much money will receive each place. Required if **is_money_places** is **1**.
            prize_data_upgrade (int): Which upgrade will each winner receive. Required if **prize_type** is **upgrades**.
            require_like_count (int): Sympathies for this week.
            require_total_like_count (int): Sympathies for all time.
            secret_answer (str): Secret answer of your account.
            tags (List[str]): Thread tags.
            reply_group (int): Allow to reply only users with chosen or higher group.
            comment_ignore_group (bool): Allow commenting if user can't post in thread.
            dont_alert_followers (bool): Don't alert followers about thread creation.
            hide_contacts (bool): Hide contacts.
            allow_ask_hidden_content (bool): Allow ask hidden content.
            schedule_date (str): Date to schedule thread creation (format: `DD-MM-YYYY`).
            schedule_time (str): Time to schedule thread creation (format: `HH:MM`).
            watch_thread_state (bool): Watch thread state.
            watch_thread (bool): Receive forum notifications of new posts in this thread.
            watch_thread_email (bool): Receive email notifications of new posts in this thread.
        """
        _path = f"/contests"
        _params = {}
        _data = {"post_body": post_body, "contest_type": contest_type, "prize_type": prize_type, "require_like_count": require_like_count, "require_total_like_count": require_total_like_count, "title": title, "title_en": title_en, "length_value": length_value, "length_option": length_option, "count_winners": count_winners, "prize_data_money": prize_data_money, "is_money_places": is_money_places, "prize_data_places": prize_data_places, "prize_data_upgrade": prize_data_upgrade, "secret_answer": secret_answer, "tags": tags, "reply_group": reply_group, "comment_ignore_group": comment_ignore_group, "dont_alert_followers": dont_alert_followers, "hide_contacts": hide_contacts, "allow_ask_hidden_content": allow_ask_hidden_content, "schedule_date": schedule_date, "schedule_time": schedule_time, "watch_thread_state": watch_thread_state, "watch_thread": watch_thread, "watch_thread_email": watch_thread_email}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def threads_claim(self, as_responder: str, as_is_market_deal: bool, as_amount: float, transfer_type: str, post_body: str, as_market_item_id: Optional[int] = None, as_data: Optional[str] = None, currency: Optional[str] = None, pay_claim: Optional[str] = None, as_funds_receipt: Optional[str] = None, as_tg_login_screenshot: Optional[str] = None, tags: Optional[List[str]] = None, hide_contacts: Optional[bool] = None, allow_ask_hidden_content: Optional[bool] = None, reply_group: Optional[int] = None, comment_ignore_group: Optional[bool] = None, dont_alert_followers: Optional[bool] = None, schedule_date: Optional[str] = None, schedule_time: Optional[str] = None, watch_thread_state: Optional[bool] = None, watch_thread: Optional[bool] = None, watch_thread_email: Optional[bool] = None) -> Any:
        """Create Claim
        
        Args:
            as_responder (str): To whom the complaint is filed. Specify a nickname or a link to the profile.
            as_is_market_deal (bool): Did you buy account on the market?
            as_market_item_id (int): Market item id. Required if **as_is_market_deal** is 1.
            as_data (str): Contacts and wallets of the responder. Specify the known data about the responder, if any. Optional if **as_is_market_deal** is 0.
            as_amount (float): Indicate the amount by which the responder deceived you.
            currency (str): Currency of Claim.
            transfer_type (str): The transaction took place through a guarantor or there was a transfer to the market with a hold? Required if **as_is_market_deal** is 0.
            pay_claim (str): Pay claim fee now or later. (Only for **transfer_type** = **notsafe**)
            as_funds_receipt (str): Funds transfer receipt. Upload a receipt for the transfer of funds, use the "View receipt" button in your wallet. May be uploaded to [Imgur](https://imgur.com/upload). Write "no" if you have not paid. Required if **as_is_market_deal** is 0.
            as_tg_login_screenshot (str): Screenshot showing the respondent's Telegram login. If the correspondence was conducted in Telegram, upload a screenshot that will display the respondent's Telegram login against the background of your dialogue. The screenshot may be uploaded to [Imgur](https://imgur.com/upload). If the correspondence was conducted elsewhere, write "no".
            tags (List[str]): Thread tags.
            hide_contacts (bool): Hide contacts.
            allow_ask_hidden_content (bool): Allow ask hidden content.
            reply_group (int): Allow to reply only users with chosen or higher group.
            comment_ignore_group (bool): Allow commenting if user can't post in thread.
            dont_alert_followers (bool): Don't alert followers about thread creation.
            schedule_date (str): Date to schedule thread creation (format: `DD-MM-YYYY`).
            schedule_time (str): Time to schedule thread creation (format: `HH:MM`).
            watch_thread_state (bool): Watch thread state.
            watch_thread (bool): Receive forum notifications of new posts in this thread.
            watch_thread_email (bool): Receive email notifications of new posts in this thread.
            post_body (str): You should describe what's happened. - describe the situation in a nutshell. If you wish, you can describe the situation in more detail using the "Spoiler" function. - attach screenshots of correspondence. You may upload to the site [Imgur](https://imgur.com/upload) - for convenience, use Ctrl + V when uploading screenshots to the album. - other evidence; - notify the respondent about the complaint you created, familiarize him with hidden content  Describe the situation in as much detail as possible.
        """
        _path = f"/claims"
        _params = {}
        _data = {"as_responder": as_responder, "as_is_market_deal": as_is_market_deal, "as_amount": as_amount, "transfer_type": transfer_type, "post_body": post_body, "as_market_item_id": as_market_item_id, "as_data": as_data, "currency": currency, "pay_claim": pay_claim, "as_funds_receipt": as_funds_receipt, "as_tg_login_screenshot": as_tg_login_screenshot, "tags": tags, "hide_contacts": hide_contacts, "allow_ask_hidden_content": allow_ask_hidden_content, "reply_group": reply_group, "comment_ignore_group": comment_ignore_group, "dont_alert_followers": dont_alert_followers, "schedule_date": schedule_date, "schedule_time": schedule_time, "watch_thread_state": watch_thread_state, "watch_thread": watch_thread, "watch_thread_email": watch_thread_email}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def threads_get(self, thread_id: int, fields_include: Optional[List[str]] = None) -> Any:
        """Get Thread
        
        Args:
            thread_id (int): Id of thread.
            fields_include (List[str]): List of fields to include.
        """
        _path = f"/threads/{thread_id}"
        _params = {"fields_include": fields_include}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def threads_edit(self, thread_id: int, title: Optional[str] = None, title_en: Optional[str] = None, prefix_id: Optional[List[int]] = None, tags: Optional[List[str]] = None, discussion_open: Optional[bool] = None, hide_contacts: Optional[bool] = None, allow_ask_hidden_content: Optional[bool] = None, reply_group: Optional[int] = None, comment_ignore_group: Optional[bool] = None) -> Any:
        """Edit thread
        
        Args:
            thread_id (int): Id of thread.
            title (str): Thread title.
            title_en (str): Thread title english.
            prefix_id (List[int]): Prefix ids. Set "0" to remove all thread prefixes.
            tags (List[str]): Thread tags.
            discussion_open (bool): Discussion state.
            hide_contacts (bool): Hide contacts.
            allow_ask_hidden_content (bool): Allow ask hidden content.
            reply_group (int): Allow to reply only users with chosen or higher group.
            comment_ignore_group (bool): Allow commenting if user can't post in thread.
        """
        _path = f"/threads/{thread_id}"
        _params = {}
        _data = {"title": title, "title_en": title_en, "prefix_id": prefix_id, "tags": tags, "discussion_open": discussion_open, "hide_contacts": hide_contacts, "allow_ask_hidden_content": allow_ask_hidden_content, "reply_group": reply_group, "comment_ignore_group": comment_ignore_group}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def threads_delete(self, thread_id: int, reason: Optional[str] = None) -> Any:
        """Delete Thread
        
        Args:
            thread_id (int): Id of thread.
            reason (str): Reason of the thread removal.
        """
        _path = f"/threads/{thread_id}"
        _params = {}
        _data = {"reason": reason}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("DELETE", _path, params=_params, json=_data)

    def threads_move(self, thread_id: int, node_id: str, title: Optional[str] = None, title_en: Optional[str] = None, prefix_id: Optional[List[int]] = None, apply_thread_prefix: Optional[bool] = None, send_alert: Optional[bool] = None) -> Any:
        """Move Thread
        
        Args:
            thread_id (int): Id of thread.
            node_id (str): Forum id.
            title (str): Thread title.
            title_en (str): Thread title english.
            prefix_id (List[int]): Prefix ids. Set "0" to remove all thread prefixes.
            apply_thread_prefix (bool): Apply thread prefix.
            send_alert (bool): Send a notification to users who are followed to target node.
        """
        _path = f"/threads/{thread_id}/move"
        _params = {}
        _data = {"node_id": node_id, "title": title, "title_en": title_en, "prefix_id": prefix_id, "apply_thread_prefix": apply_thread_prefix, "send_alert": send_alert}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def threads_bump(self, thread_id: int) -> Any:
        """Bump Thread
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/threads/{thread_id}/bump"
        _params = {}
        return self._request("POST", _path, params=_params)

    def threads_hide(self, thread_id: int) -> Any:
        """Hide Thread
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/threads/{thread_id}/hide"
        _params = {}
        return self._request("POST", _path, params=_params)

    def threads_star(self, thread_id: int) -> Any:
        """Bookmark Thread
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/threads/{thread_id}/star"
        _params = {}
        return self._request("POST", _path, params=_params)

    def threads_unstar(self, thread_id: int) -> Any:
        """Unbookmark Thread
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/threads/{thread_id}/star"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def threads_followers(self, thread_id: int) -> Any:
        """Get Thread Followers
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/threads/{thread_id}/followers"
        _params = {}
        return self._request("GET", _path, params=_params)

    def threads_follow(self, thread_id: int, email: Optional[bool] = None) -> Any:
        """Follow Thread
        
        Args:
            thread_id (int): Id of thread.
            email (bool): Whether to receive notification as email.
        """
        _path = f"/threads/{thread_id}/followers"
        _params = {}
        _data = {"email": email}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def threads_unfollow(self, thread_id: int) -> Any:
        """Unfollow Thread
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/threads/{thread_id}/followers"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def threads_followed(self, total: Optional[bool] = None, fields_include: Optional[List[str]] = None) -> Any:
        """Get Followed Threads
        
        Args:
            total (bool): If included in the request, only the thread count is returned as **threads_total**.
            fields_include (List[str]): List of fields to include.
        """
        _path = f"/threads/followed"
        _params = {"total": total, "fields_include": fields_include}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def threads_navigation(self, thread_id: int) -> Any:
        """Get Navigation Elements
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/threads/{thread_id}/navigation"
        _params = {}
        return self._request("GET", _path, params=_params)

    def threads_poll_get(self, thread_id: int) -> Any:
        """Get Poll
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/threads/{thread_id}/poll"
        _params = {}
        return self._request("GET", _path, params=_params)

    def threads_poll_vote(self, thread_id: int, response_id: Optional[int] = None, response_ids: Optional[List[int]] = None) -> Any:
        """Vote Poll
        
        Args:
            thread_id (int): Id of thread.
            response_id (int): The id of the response to vote for. Can be skipped if **response_ids** set.
            response_ids (List[int]): An array of ids of responses (if the poll allows multiple choices).
        """
        _path = f"/threads/{thread_id}/poll/votes"
        _params = {}
        _data = {"response_id": response_id, "response_ids": response_ids}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def threads_unread(self, limit: Optional[int] = None, forum_id: Optional[int] = None, data_limit: Optional[int] = None) -> Any:
        """Get Unread Threads
        
        Args:
            limit (int): Maximum number of result threads. The limit may get decreased if the value is too large (depending on the system configuration).
            forum_id (int): Id of the container forum to search for threads. Child forums of the specified forum will be included in the search.
            data_limit (int): Number of thread data to be returned. Default value is 20.
        """
        _path = f"/threads/new"
        _params = {"limit": limit, "forum_id": forum_id, "data_limit": data_limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def threads_recent(self, days: Optional[int] = None, limit: Optional[int] = None, forum_id: Optional[int] = None, data_limit: Optional[int] = None) -> Any:
        """Get Recent Threads
        
        Args:
            days (int): Maximum number of days to search for threads.
            limit (int): Maximum number of result threads. The limit may get decreased if the value is too large.
            forum_id (int): Id of the container forum to search for threads. Child forums of the specified forum will be included in the search.
            data_limit (int): Number of thread data to be returned. Default value is 20.
        """
        _path = f"/threads/recent"
        _params = {"days": days, "limit": limit, "forum_id": forum_id, "data_limit": data_limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def threads_finish(self, thread_id: int) -> Any:
        """Finish Contest
        
        Args:
            thread_id (int): Id of thread.
        """
        _path = f"/contests/{thread_id}/finish"
        _params = {}
        return self._request("POST", _path, params=_params)

    def posts_list(self, thread_id: Optional[int] = None, page_of_post_id: Optional[int] = None, page: Optional[int] = None, limit: Optional[int] = None, order: Optional[str] = None) -> Any:
        """Get Posts
        
        Args:
            thread_id (int): Id of the containing thread.
            page_of_post_id (int): Id of a post, posts that are in the same page with the specified post will be returned. **thread_id** may be skipped.
            page (int): Page number of posts.
            limit (int): Number of posts in a page.
            order (str): Ordering of posts.
        """
        _path = f"/posts"
        _params = {"thread_id": thread_id, "page_of_post_id": page_of_post_id, "page": page, "limit": limit, "order": order}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def posts_create(self, post_body: str, thread_id: Optional[int] = None, quote_post_id: Optional[int] = None) -> Any:
        """Create Post
        
        Args:
            post_body (str): Content of the new post.
            thread_id (int): Id of the target thread. **quote_post_id** can be skipped if this parameter is provided.
            quote_post_id (int): Id of the quote post. **thread_id** can be skipped if this parameter is provided.
        """
        _path = f"/posts"
        _params = {}
        _data = {"post_body": post_body, "thread_id": thread_id, "quote_post_id": quote_post_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def posts_get(self, post_id: int) -> Any:
        """Get Post
        
        Args:
            post_id (int): Id of post.
        """
        _path = f"/posts/{post_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def posts_edit(self, post_id: int, post_body: Optional[str] = None) -> Any:
        """Edit Post
        
        Args:
            post_id (int): Id of post.
            post_body (str): Content of the post.
        """
        _path = f"/posts/{post_id}"
        _params = {}
        _data = {"post_body": post_body}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def posts_delete(self, post_id: int, reason: Optional[str] = None) -> Any:
        """Delete Post
        
        Args:
            post_id (int): Id of post.
            reason (str): Reason of the post removal.
        """
        _path = f"/posts/{post_id}"
        _params = {}
        _data = {"reason": reason}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("DELETE", _path, params=_params, json=_data)

    def posts_likes(self, post_id: int, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Post Likes
        
        Args:
            post_id (int): Id of post.
            page (int): Page number of users.
            limit (int): Number of users in a page.
        """
        _path = f"/posts/{post_id}/likes"
        _params = {"page": page, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def posts_like(self, post_id: int) -> Any:
        """Like Post
        
        Args:
            post_id (int): Id of post.
        """
        _path = f"/posts/{post_id}/likes"
        _params = {}
        return self._request("POST", _path, params=_params)

    def posts_unlike(self, post_id: int) -> Any:
        """Unlike Post
        
        Args:
            post_id (int): Id of post.
        """
        _path = f"/posts/{post_id}/likes"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def posts_report_reasons(self, post_id: int) -> Any:
        """Get Post Report Reasons
        
        Args:
            post_id (int): Id of post.
        """
        _path = f"/posts/{post_id}/report"
        _params = {}
        return self._request("GET", _path, params=_params)

    def posts_report(self, post_id: int, message: str) -> Any:
        """Report Post
        
        Args:
            post_id (int): Id of post.
            message (str): Reason of the report.
        """
        _path = f"/posts/{post_id}/report"
        _params = {}
        _data = {"message": message}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def posts_comments_get(self, post_id: int, before: Optional[int] = None, before_comment: Optional[int] = None) -> Any:
        """Get Post Comments
        
        Args:
            post_id (int): Id of post.
            before (int): The time in milliseconds (e.g. 1652177794083) before last comment date.
            before_comment (int): Comment id to get older comments.
        """
        _path = f"/posts/comments"
        _params = {"post_id": post_id, "before": before, "before_comment": before_comment}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def posts_comments_create(self, post_id: int, comment_body: str) -> Any:
        """Create Post Comment
        
        Args:
            post_id (int): Id of post.
            comment_body (str): Content of the a post comment.
        """
        _path = f"/posts/comments"
        _params = {}
        _data = {"post_id": post_id, "comment_body": comment_body}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def posts_comments_edit(self, post_comment_id: int, comment_body: str) -> Any:
        """Edit Post Comment
        
        Args:
            post_comment_id (int): Id of post.
            comment_body (str): Content of the new post comment.
        """
        _path = f"/posts/comments"
        _params = {}
        _data = {"post_comment_id": post_comment_id, "comment_body": comment_body}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def posts_comments_delete(self, post_comment_id: int, reason: Optional[str] = None) -> Any:
        """Delete Post Comment
        
        Args:
            post_comment_id (int): Id of post comment.
            reason (str): Reason of a post comment removal.
        """
        _path = f"/posts/comments"
        _params = {}
        _data = {"post_comment_id": post_comment_id, "reason": reason}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("DELETE", _path, params=_params, json=_data)

    def posts_comments_report(self, post_comment_id: int, message: str) -> Any:
        """Report Post Comment
        
        Args:
            post_comment_id (int): Id of post comment.
            message (str): Reason of the report.
        """
        _path = f"/posts/comments/report"
        _params = {}
        _data = {"post_comment_id": post_comment_id, "message": message}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def users_list(self, page: Optional[int] = None, limit: Optional[int] = None, fields_include: Optional[List[str]] = None) -> Any:
        """Get Users
        
        Args:
            page (int): Page number of users.
            limit (int): Number of users in a page.
            fields_include (List[str]): List of fields to include.
        """
        _path = f"/users"
        _params = {"page": page, "limit": limit, "fields_include": fields_include}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_fields(self) -> Any:
        """Get User Fields
        """
        _path = f"/users/fields"
        _params = {}
        return self._request("GET", _path, params=_params)

    def users_find(self, username: Optional[str] = None, custom_fields: Optional[Dict[str, Any]] = None, fields_include: Optional[List[str]] = None) -> Any:
        """Find Users
        
        Args:
            username (str): Username to filter. Usernames start with the query will be returned.
            custom_fields (Dict[str, Any]): Custom fields to filter. Example: **custom_fields[telegram]=telegramLogin**.
            fields_include (List[str]): List of fields to include.
        """
        _path = f"/users/find"
        _params = {"username": username, "custom_fields": custom_fields, "fields_include": fields_include}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_get(self, user_id: UserIDModel, fields_include: Optional[List[str]] = None) -> Any:
        """Get User
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            fields_include (List[str]): List of fields to include.
        """
        _path = f"/users/{user_id}"
        _params = {"fields_include": fields_include}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_edit(self, user_id: UserIDModel, username: Optional[str] = None, user_title: Optional[str] = None, display_group_id: Optional[int] = None, display_icon_group_id: Optional[int] = None, display_banner_id: Optional[int] = None, conv_welcome_message: Optional[str] = None, user_dob_day: Optional[int] = None, user_dob_month: Optional[int] = None, user_dob_year: Optional[int] = None, secret_answer: Optional[str] = None, secret_answer_type: Optional[int] = None, short_link: Optional[str] = None, language_id: Optional[int] = None, gender: Optional[str] = None, timezone: Optional[str] = None, receive_admin_email: Optional[bool] = None, activity_visible: Optional[bool] = None, show_dob_date: Optional[bool] = None, show_dob_year: Optional[bool] = None, hide_username_change_logs: Optional[bool] = None, allow_view_profile: Optional[str] = None, allow_post_profile: Optional[str] = None, allow_send_personal_conversation: Optional[str] = None, allow_invite_group: Optional[str] = None, allow_receive_news_feed: Optional[str] = None, alert: Optional[Dict[str, Any]] = None, fields: Optional[Dict[str, Any]] = None) -> Any:
        """Edit User
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            username (str): New username.
            user_title (str): New custom title of the user.
            display_group_id (int): Id of the group you want to display.
            display_icon_group_id (int): Id of the icon group you want to display.
            display_banner_id (int): Id of the banner you want to display.
            conv_welcome_message (str): This message is shown when someone wants to write to you.
            user_dob_day (int): Your date of birth (day).
            user_dob_month (int): Your date of birth (month).
            user_dob_year (int): Your date of birth (year).
            secret_answer (str): Secret answer.
            secret_answer_type (int): Secret answer type.
            short_link (str): Profile short link.
            language_id (int): User interface language ID.
            gender (str): User gender.
            timezone (str): User timezone.
            receive_admin_email (bool): Whether to receive admin emails.
            activity_visible (bool): Whether user activity is visible.
            show_dob_date (bool): Show date of birth (day and month).
            show_dob_year (bool): Show year of birth.
            hide_username_change_logs (bool): Hide username change logs.
            allow_view_profile (str): Who can view your profile.
            allow_post_profile (str): Who can post on your profile.
            allow_send_personal_conversation (str): Who can send you personal conversations.
            allow_invite_group (str): Who can invite you to groups.
            allow_receive_news_feed (str): Who can see your news feed.
            alert (Dict[str, Any]): Alert settings.
            fields (Dict[str, Any]): Custom user profile fields.
        """
        _path = f"/users/{user_id}"
        _params = {}
        _data = {"username": username, "user_title": user_title, "display_group_id": display_group_id, "display_icon_group_id": display_icon_group_id, "display_banner_id": display_banner_id, "conv_welcome_message": conv_welcome_message, "user_dob_day": user_dob_day, "user_dob_month": user_dob_month, "user_dob_year": user_dob_year, "secret_answer": secret_answer, "secret_answer_type": secret_answer_type, "short_link": short_link, "language_id": language_id, "gender": gender, "timezone": timezone, "receive_admin_email": receive_admin_email, "activity_visible": activity_visible, "show_dob_date": show_dob_date, "show_dob_year": show_dob_year, "hide_username_change_logs": hide_username_change_logs, "allow_view_profile": allow_view_profile, "allow_post_profile": allow_post_profile, "allow_send_personal_conversation": allow_send_personal_conversation, "allow_invite_group": allow_invite_group, "allow_receive_news_feed": allow_receive_news_feed, "alert": alert, "fields": fields}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def users_claims(self, user_id: UserIDModel, type_: Optional[str] = None, claim_state: Optional[str] = None) -> Any:
        """Get User Claims
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            type_ (str): Filter claims by their type.
            claim_state (str): Filter claims by their state.
        """
        _path = f"/users/{user_id}/claims"
        _params = {"type": type_, "claim_state": claim_state}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_avatar_upload(self, user_id: UserIDModel, avatar: str, x: Optional[int] = None, y: Optional[int] = None, crop: Optional[int] = None) -> Any:
        """Upload Avatar
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            avatar (str): Binary data of the avatar.
            x (int): The starting point of the selection by width. Default value - 0
            y (int): The starting point of the selection by height. Default value - 0
            crop (int): Selection size.
        """
        _path = f"/users/{user_id}/avatar"
        _params = {}
        _data = {"avatar": avatar, "x": x, "y": y, "crop": crop}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def users_avatar_delete(self, user_id: UserIDModel) -> Any:
        """Delete Avatar
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
        """
        _path = f"/users/{user_id}/avatar"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def users_avatar_crop(self, user_id: UserIDModel, x: Optional[int] = None, y: Optional[int] = None, crop: Optional[int] = None) -> Any:
        """Crop Avatar
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            x (int): The starting point of the selection by width. Default value - 0
            y (int): The starting point of the selection by height. Default value - 0
            crop (int): Selection size.
        """
        _path = f"/users/{user_id}/avatar/crop"
        _params = {}
        _data = {"x": x, "y": y, "crop": crop}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def users_background_upload(self, user_id: UserIDModel, background: str, x: Optional[int] = None, y: Optional[int] = None, crop: Optional[int] = None) -> Any:
        """Upload Background
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            background (str): Binary data of the background. Background image must be 1920x1080 pixels
            x (int): The starting point of the selection by width. Default value - 0
            y (int): The starting point of the selection by height. Default value - 0
            crop (int): Selection size.
        """
        _path = f"/users/{user_id}/background"
        _params = {}
        _data = {"background": background, "x": x, "y": y, "crop": crop}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def users_background_delete(self, user_id: UserIDModel) -> Any:
        """Delete Background
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
        """
        _path = f"/users/{user_id}/background"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def users_background_crop(self, user_id: UserIDModel, x: Optional[int] = None, y: Optional[int] = None, crop: Optional[int] = None) -> Any:
        """Crop Background
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            x (int): The starting point of the selection by width. Default value - 0
            y (int): The starting point of the selection by height. Default value - 0
            crop (int): Selection size.
        """
        _path = f"/users/{user_id}/background/crop"
        _params = {}
        _data = {"x": x, "y": y, "crop": crop}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def users_followers(self, user_id: UserIDModel, order: Optional[str] = None, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get User Followers
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            order (str): Ordering of followers.
            page (int): Page number of followers.
            limit (int): Number of followers in a page.
        """
        _path = f"/users/{user_id}/followers"
        _params = {"order": order, "page": page, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_follow(self, user_id: UserIDModel) -> Any:
        """Follow User
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
        """
        _path = f"/users/{user_id}/followers"
        _params = {}
        return self._request("POST", _path, params=_params)

    def users_unfollow(self, user_id: UserIDModel) -> Any:
        """Unfollow User
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
        """
        _path = f"/users/{user_id}/followers"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def users_followings(self, user_id: UserIDModel, order: Optional[str] = None, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Followed Users By User
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            order (str): Ordering of users.
            page (int): Page number of users.
            limit (int): Number of users in a page.
        """
        _path = f"/users/{user_id}/followings"
        _params = {"order": order, "page": page, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_likes(self, user_id: UserIDModel, node_id: Optional[int] = None, like_type: Optional[str] = None, type_: Optional[str] = None, page: Optional[int] = None, content_type: Optional[str] = None, search_user_id: Optional[int] = None, stats: Optional[bool] = None) -> Any:
        """Get User Likes
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            node_id (int): Filter by forum section.
            like_type (str): Like type.
            type_ (str): Likes type.
            page (int): Page number.
            content_type (str): Content type.
            search_user_id (int): Get only likes from specified user.
            stats (bool): Show weekly statistics.
        """
        _path = f"/users/{user_id}/likes"
        _params = {"node_id": node_id, "like_type": like_type, "type": type_, "page": page, "content_type": content_type, "search_user_id": search_user_id, "stats": stats}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_ignored(self, total: Optional[bool] = None) -> Any:
        """Get Ignored Users
        
        Args:
            total (bool): If included in the request, only the user count is returned as **users_total**.
        """
        _path = f"/users/ignored"
        _params = {"total": total}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_ignore(self, user_id: UserIDModel) -> Any:
        """Ignore User
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
        """
        _path = f"/users/{user_id}/ignore"
        _params = {}
        return self._request("POST", _path, params=_params)

    def users_ignore_edit(self, user_id: UserIDModel, ignore_conversations: Optional[bool] = None, ignore_content: Optional[bool] = None, restrict_view_profile: Optional[bool] = None) -> Any:
        """Edit Ignoring Options
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            ignore_conversations (bool): Ignore user's conversations.
            ignore_content (bool): Ignore user's content.
            restrict_view_profile (bool): Restrict user from viewing your profile.
        """
        _path = f"/users/{user_id}/ignore"
        _params = {"ignore_conversations": ignore_conversations, "ignore_content": ignore_content, "restrict_view_profile": restrict_view_profile}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("PUT", _path, params=_params)

    def users_unignore(self, user_id: UserIDModel) -> Any:
        """Unignore User
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
        """
        _path = f"/users/{user_id}/ignore"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def users_contents(self, user_id: UserIDModel, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Contents
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            page (int): Page number of contents.
            limit (int): Number of contents in a page.
        """
        _path = f"/users/{user_id}/timeline"
        _params = {"page": page, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def users_trophies(self, user_id: UserIDModel) -> Any:
        """Get Trophies
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
        """
        _path = f"/users/{user_id}/trophies"
        _params = {}
        return self._request("GET", _path, params=_params)

    def users_secret_answer_types(self) -> Any:
        """Get Secret Answer Types
        """
        _path = f"/users/secret-answer/types"
        _params = {}
        return self._request("GET", _path, params=_params)

    def users_sa_reset(self) -> Any:
        """Reset Secret Answer
        """
        _path = f"/account/secret-answer/reset"
        _params = {}
        return self._request("POST", _path, params=_params)

    def users_sa_cancel_reset(self) -> Any:
        """Cancel Secret Answer Reset
        """
        _path = f"/account/secret-answer/reset"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def profile_posts_list(self, user_id: UserIDModel, posts_user_id: Optional[int] = None, page: Optional[int] = None, limit: Optional[int] = None, fields_include: Optional[List[str]] = None) -> Any:
        """Get Profile Posts
        
        Args:
            user_id (UserIDModel): User ID. > You can use shortlink `me` to interact with your profile.
            posts_user_id (int): Filter to get only posts from the specified user.
            page (int): Page number of contents.
            limit (int): Number of contents in a page.
            fields_include (List[str]): List of fields to include.
        """
        _path = f"/users/{user_id}/profile-posts"
        _params = {"posts_user_id": posts_user_id, "page": page, "limit": limit, "fields_include": fields_include}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def profile_posts_get(self, profile_post_id: int) -> Any:
        """Get Profile Post
        
        Args:
            profile_post_id (int): Id of profile post.
        """
        _path = f"/profile-posts/{profile_post_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def profile_posts_edit(self, profile_post_id: int, post_body: Optional[str] = None, disable_comments: Optional[bool] = None) -> Any:
        """Edit Profile Post
        
        Args:
            profile_post_id (int): Id of profile post.
            post_body (str): New content of the profile post.
            disable_comments (bool): Disable comments.
        """
        _path = f"/profile-posts/{profile_post_id}"
        _params = {}
        _data = {"post_body": post_body, "disable_comments": disable_comments}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def profile_posts_delete(self, profile_post_id: int, reason: Optional[str] = None) -> Any:
        """Delete Profile Post
        
        Args:
            profile_post_id (int): Id of profile post.
            reason (str): Reason of the profile post removal.
        """
        _path = f"/profile-posts/{profile_post_id}"
        _params = {"reason": reason}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("DELETE", _path, params=_params)

    def profile_posts_report_reasons(self, profile_post_id: int) -> Any:
        """Get Profile Post Report Reasons
        
        Args:
            profile_post_id (int): Id of profile post.
        """
        _path = f"/profile-posts/{profile_post_id}/report"
        _params = {}
        return self._request("GET", _path, params=_params)

    def profile_posts_report(self, profile_post_id: int, message: str) -> Any:
        """Report a Profile Post
        
        Args:
            profile_post_id (int): Id of profile post.
            message (str): Reason of the report.
        """
        _path = f"/profile-posts/{profile_post_id}/report"
        _params = {}
        _data = {"message": message}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def profile_posts_create(self, user_id: UserIDModel, post_body: str) -> Any:
        """Create Profile Post
        
        Args:
            user_id (UserIDModel): 
            post_body (str): Content of a profile post.
        """
        _path = f"/profile-posts"
        _params = {}
        _data = {"user_id": user_id, "post_body": post_body}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def profile_posts_stick(self, profile_post_id: int) -> Any:
        """Stick Profile Post
        
        Args:
            profile_post_id (int): Id of profile post.
        """
        _path = f"/profile-posts/{profile_post_id}/stick"
        _params = {}
        return self._request("POST", _path, params=_params)

    def profile_posts_unstick(self, profile_post_id: int) -> Any:
        """Unstick Profile Post
        
        Args:
            profile_post_id (int): Id of profile post.
        """
        _path = f"/profile-posts/{profile_post_id}/stick"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def profile_posts_likes(self, profile_post_id: int) -> Any:
        """Get Profile Post Likes
        
        Args:
            profile_post_id (int): Id of profile post.
        """
        _path = f"/profile-posts/{profile_post_id}/likes"
        _params = {}
        return self._request("GET", _path, params=_params)

    def profile_posts_like(self, profile_post_id: int) -> Any:
        """Like Profile Post
        
        Args:
            profile_post_id (int): Id of profile post.
        """
        _path = f"/profile-posts/{profile_post_id}/likes"
        _params = {}
        return self._request("POST", _path, params=_params)

    def profile_posts_unlike(self, profile_post_id: int) -> Any:
        """Unlike Profile Post
        
        Args:
            profile_post_id (int): Id of profile post.
        """
        _path = f"/profile-posts/{profile_post_id}/likes"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def profile_posts_comments_list(self, profile_post_id: int, before: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Profile Post Comments
        
        Args:
            profile_post_id (int): Id of profile post.
            before (int): Date to get older comments. Please note that this entry point does not support the page parameter but it still does support **limit**.
            limit (int): Number of profile posts in a page.
        """
        _path = f"/profile-posts/comments"
        _params = {"profile_post_id": profile_post_id, "before": before, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def profile_posts_comments_create(self, profile_post_id: int, comment_body: str) -> Any:
        """Create Profile Post Comment
        
        Args:
            profile_post_id (int): Id of profile post.
            comment_body (str): Content of the new profile post comment.
        """
        _path = f"/profile-posts/comments"
        _params = {}
        _data = {"profile_post_id": profile_post_id, "comment_body": comment_body}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def profile_posts_comments_edit(self, comment_id: int, comment_body: str) -> Any:
        """Edit Profile Post Comment
        
        Args:
            comment_id (int): Id of profile post comment.
            comment_body (str): New content for the profile post comment.
        """
        _path = f"/profile-posts/comments"
        _params = {}
        _data = {"comment_id": comment_id, "comment_body": comment_body}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def profile_posts_comments_delete(self, comment_id: int) -> Any:
        """Delete Profile Post Comment
        
        Args:
            comment_id (int): Id of profile post comment.
        """
        _path = f"/profile-posts/comments"
        _params = {}
        _data = {"comment_id": comment_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("DELETE", _path, params=_params, json=_data)

    def profile_posts_comments_get(self, profile_post_id: int, comment_id: int) -> Any:
        """Get Profile Post Comment
        
        Args:
            profile_post_id (int): Id of profile post.
            comment_id (int): Id of profile post comment.
        """
        _path = f"/profile-posts/{profile_post_id}/comments/{comment_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def profile_posts_comments_report(self, comment_id: int, message: str) -> Any:
        """Report a Profile Post Comment
        
        Args:
            comment_id (int): Id of profile post comment.
            message (str): Reason of the report.
        """
        _path = f"/profile-posts/comments/{comment_id}/report"
        _params = {}
        _data = {"message": message}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def conversations_list(self, folder: Optional[str] = None, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Conversations
        
        Args:
            folder (str): Filter conversations by folder.
            page (int): Page number of conversations.
            limit (int): Number of conversations in a page.
        """
        _path = f"/conversations"
        _params = {"folder": folder, "page": page, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def conversations_create(self, recipient_id: Optional[int] = None, recipients: Optional[List[str]] = None, is_group: Optional[bool] = None, title: Optional[str] = None, open_invite: Optional[bool] = None, allow_edit_messages: Optional[bool] = None, allow_sticky_messages: Optional[bool] = None, allow_delete_own_messages: Optional[bool] = None, message_body: Optional[str] = None) -> Any:
        """Create Conversation
        
        Args:
            recipient_id (int): Id of recipient. Required if **is_group=false**.
            recipients (List[str]): List of recipients username's. Max recipients count is 10. Required if **is_group=true**.
            is_group (bool): Is group. Set **false** if personal conversation, or set **true** if group.
            title (str): The title of new conversation. Required if **is_group=1**.
            open_invite (bool): Open invite.
            allow_edit_messages (bool): Allow edit messages.
            allow_sticky_messages (bool): Allow members to stick messages.
            allow_delete_own_messages (bool): Allow members to delete their own messages.
            message_body (str): First message. Required if **is_group**=false
        """
        _path = f"/conversations"
        _params = {}
        _data = {"recipient_id": recipient_id, "recipients": recipients, "is_group": is_group, "title": title, "open_invite": open_invite, "allow_edit_messages": allow_edit_messages, "allow_sticky_messages": allow_sticky_messages, "allow_delete_own_messages": allow_delete_own_messages, "message_body": message_body}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def conversations_update(self, conversation_id: int, title: Optional[str] = None, open_invite: Optional[bool] = None, history_open: Optional[bool] = None, allow_edit_messages: Optional[bool] = None, allow_sticky_messages: Optional[bool] = None, allow_delete_own_messages: Optional[bool] = None) -> Any:
        """Edit Conversation
        
        Args:
            conversation_id (int): Id of conversation.
            title (str): New conversation title.
            open_invite (bool): Allow members to invite others.
            history_open (bool): Make conversation history visible to new members.
            allow_edit_messages (bool): Allow members to edit their own messages.
            allow_sticky_messages (bool): Allow members to stick messages.
            allow_delete_own_messages (bool): Allow members to delete their own messages.
        """
        _path = f"/conversations"
        _params = {}
        _data = {"conversation_id": conversation_id, "title": title, "open_invite": open_invite, "history_open": history_open, "allow_edit_messages": allow_edit_messages, "allow_sticky_messages": allow_sticky_messages, "allow_delete_own_messages": allow_delete_own_messages}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def conversations_delete(self, conversation_id: int, delete_type: str) -> Any:
        """Leave Conversation
        
        Args:
            conversation_id (int): Id of conversation.
            delete_type (str): Deletion type.
        """
        _path = f"/conversations"
        _params = {}
        _data = {"conversation_id": conversation_id, "delete_type": delete_type}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("DELETE", _path, params=_params, json=_data)

    def conversations_start(self, user_id: UserIDModel) -> Any:
        """Start Conversation
        
        Args:
            user_id (UserIDModel): 
        """
        _path = f"/conversations/start"
        _params = {}
        _data = {"user_id": user_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def conversations_save(self, link: str) -> Any:
        """Send Content To Saved Messages
        
        Args:
            link (str): Content url.
        """
        _path = f"/conversations/save"
        _params = {}
        _data = {"link": link}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def conversations_get(self, conversation_id: int) -> Any:
        """Get Conversation
        
        Args:
            conversation_id (int): Id of conversation.
        """
        _path = f"/conversations/{conversation_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def conversations_messages_list(self, conversation_id: int, page: Optional[int] = None, limit: Optional[int] = None, order: Optional[str] = None, before: Optional[int] = None, after: Optional[int] = None) -> Any:
        """Get Conversation Messages
        
        Args:
            conversation_id (int): Id of conversation.
            page (int): Page number of messages.
            limit (int): Number of messages in a page.
            order (str): Ordering of messages.
            before (int): Date to get older messages.
            after (int): Date to get newer messages.
        """
        _path = f"/conversations/{conversation_id}/messages"
        _params = {"page": page, "limit": limit, "order": order, "before": before, "after": after}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def conversations_messages_create(self, conversation_id: int, message_body: str, reply_message_id: Optional[int] = None) -> Any:
        """Create Conversation Message
        
        Args:
            conversation_id (int): Id of conversation.
            reply_message_id (int): ID of the message being replied to.
            message_body (str): Content of the new message.
        """
        _path = f"/conversations/{conversation_id}/messages"
        _params = {}
        _data = {"message_body": message_body, "reply_message_id": reply_message_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def conversations_search(self, q: Optional[str] = None, conversation_id: Optional[int] = None, search_recipients: Optional[bool] = None) -> Any:
        """Search Conversations Messages
        
        Args:
            q (str): Search query string.
            conversation_id (int): Id of conversation.
            search_recipients (bool): Search for recipients.
        """
        _path = f"/conversations/search"
        _params = {}
        _data = {"q": q, "conversation_id": conversation_id, "search_recipients": search_recipients}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def conversations_messages_get(self, message_id: int) -> Any:
        """Get Conversation Message
        
        Args:
            message_id (int): Id of message.
        """
        _path = f"/conversations/messages/{message_id}"
        _params = {}
        return self._request("GET", _path, params=_params)

    def conversations_messages_edit(self, conversation_id: int, message_id: int, message_body: str) -> Any:
        """Edit Conversation Message
        
        Args:
            conversation_id (int): Id of conversation.
            message_id (int): Id of message.
            message_body (str): New content of the message.
        """
        _path = f"/conversations/{conversation_id}/messages/{message_id}"
        _params = {}
        _data = {"message_body": message_body}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def conversations_messages_delete(self, conversation_id: int, message_id: int) -> Any:
        """Delete Conversation Message
        
        Args:
            conversation_id (int): Id of conversation.
            message_id (int): Id of message.
        """
        _path = f"/conversations/{conversation_id}/messages/{message_id}"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def conversations_invite(self, conversation_id: int, recipients: List[str]) -> Any:
        """Invite Users to Conversation
        
        Args:
            conversation_id (int): Id of conversation.
            recipients (List[str]): List of recipients username's.
        """
        _path = f"/conversations/{conversation_id}/invite"
        _params = {}
        _data = {"recipients": recipients}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def conversations_kick(self, conversation_id: int, user_id: int) -> Any:
        """Kick User from Conversation
        
        Args:
            conversation_id (int): Id of conversation.
            user_id (int): Id of user to kick from conversation.
        """
        _path = f"/conversations/{conversation_id}/kick"
        _params = {}
        _data = {"user_id": user_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def conversations_read(self, conversation_id: int) -> Any:
        """Read a Conversation
        
        Args:
            conversation_id (int): Id of conversation.
        """
        _path = f"/conversations/{conversation_id}/read"
        _params = {}
        return self._request("POST", _path, params=_params)

    def conversations_read_all(self) -> Any:
        """Read All Conversations
        """
        _path = f"/conversations/read-all"
        _params = {}
        return self._request("POST", _path, params=_params)

    def conversations_messages_stick(self, conversation_id: int, message_id: int) -> Any:
        """Stick Conversation Message
        
        Args:
            conversation_id (int): Id of conversation.
            message_id (int): Id of message.
        """
        _path = f"/conversations/{conversation_id}/messages/{message_id}/stick"
        _params = {}
        return self._request("POST", _path, params=_params)

    def conversations_messages_unstick(self, conversation_id: int, message_id: int) -> Any:
        """Unstick Conversation Message
        
        Args:
            conversation_id (int): Id of conversation.
            message_id (int): Id of message.
        """
        _path = f"/conversations/{conversation_id}/messages/{message_id}/stick"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def conversations_star(self, conversation_id: int) -> Any:
        """Star Conversation
        
        Args:
            conversation_id (int): Id of conversation.
        """
        _path = f"/conversations/{conversation_id}/star"
        _params = {}
        return self._request("POST", _path, params=_params)

    def conversations_unstar(self, conversation_id: int) -> Any:
        """Unstar Conversation
        
        Args:
            conversation_id (int): Id of conversation.
        """
        _path = f"/conversations/{conversation_id}/star"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def conversations_alerts_enable(self, conversation_id: int) -> Any:
        """Enable Conversation Alerts
        
        Args:
            conversation_id (int): Id of conversation.
        """
        _path = f"/conversations/{conversation_id}/alerts"
        _params = {}
        return self._request("POST", _path, params=_params)

    def conversations_alerts_disable(self, conversation_id: int) -> Any:
        """Disable Conversation Alerts
        
        Args:
            conversation_id (int): Id of conversation.
        """
        _path = f"/conversations/{conversation_id}/alerts"
        _params = {}
        return self._request("DELETE", _path, params=_params)

    def notifications_list(self, type_: Optional[str] = None, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Notifications
        
        Args:
            type_ (str): Filter notifications by their type.
            page (int): Page number of notifications.
            limit (int): Number of notifications in a page.
        """
        _path = f"/notifications"
        _params = {"type": type_, "page": page, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def notifications_get(self, notification_id: int) -> Any:
        """Get Notification
        
        Args:
            notification_id (int): Id of notification.
        """
        _path = f"/notifications/{notification_id}/content"
        _params = {}
        return self._request("GET", _path, params=_params)

    def notifications_read(self, notification_id: Optional[int] = None) -> Any:
        """Mark Notification Read
        
        Args:
            notification_id (int): If notification_id is omitted, it's mark all existing notifications as read.
        """
        _path = f"/notifications/read"
        _params = {}
        _data = {"notification_id": notification_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def tags_popular(self) -> Any:
        """Get Popular Tags
        """
        _path = f"/tags"
        _params = {}
        return self._request("GET", _path, params=_params)

    def tags_list(self, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Tags
        
        Args:
            page (int): Page number of tags list.
            limit (int): Number of results in a page.
        """
        _path = f"/tags/list"
        _params = {"page": page, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def tags_get(self, tag_id: int, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Tagged Content
        
        Args:
            tag_id (int): Id of tag.
            page (int): Page number of tagged contents.
            limit (int): Number of tagged contents in a page.
        """
        _path = f"/tags/{tag_id}"
        _params = {"page": page, "limit": limit}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def tags_find(self, tag: str) -> Any:
        """Get Filtered Content
        
        Args:
            tag (str): tag to filter. Tags start with the query will be returned.
        """
        _path = f"/tags/find"
        _params = {"tag": tag}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def search_all(self, q: Optional[str] = None, tag: Optional[str] = None, forum_id: Optional[int] = None, user_id: Optional[UserIDModel] = None, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Search
        
        Args:
            q (str): Search query. Can be skipped if **user_id** is set.
            tag (str): Tag to search for tagged contents.
            forum_id (int): Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
            user_id (UserIDModel): 
            page (int): Page number of results.
            limit (int): Number of results in a page.
        """
        _path = f"/search"
        _params = {}
        _data = {"q": q, "tag": tag, "forum_id": forum_id, "user_id": user_id, "page": page, "limit": limit}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def search_threads(self, q: Optional[str] = None, tag: Optional[str] = None, forum_id: Optional[int] = None, user_id: Optional[UserIDModel] = None, page: Optional[int] = None, limit: Optional[int] = None, data_limit: Optional[int] = None) -> Any:
        """Search Thread
        
        Args:
            q (str): Search query. Can be skipped if **user_id** is set.
            tag (str): Tag to search for tagged contents.
            forum_id (int): Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
            user_id (UserIDModel): 
            page (int): Page number of results.
            limit (int): Number of results in a page.
            data_limit (int): Number of thread data to be returned.
        """
        _path = f"/search/threads"
        _params = {}
        _data = {"q": q, "tag": tag, "forum_id": forum_id, "user_id": user_id, "page": page, "limit": limit, "data_limit": data_limit}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def search_posts(self, q: Optional[str] = None, tag: Optional[str] = None, forum_id: Optional[int] = None, user_id: Optional[UserIDModel] = None, page: Optional[int] = None, limit: Optional[int] = None, data_limit: Optional[int] = None) -> Any:
        """Search Post
        
        Args:
            q (str): Search query. Can be skipped if **user_id** is set.
            tag (str): Tag to search for tagged contents.
            forum_id (int): Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
            user_id (UserIDModel): 
            page (int): Page number of results.
            limit (int): Number of results in a page.
            data_limit (int): Number of post data to be returned.
        """
        _path = f"/search/posts"
        _params = {}
        _data = {"q": q, "tag": tag, "forum_id": forum_id, "user_id": user_id, "page": page, "limit": limit, "data_limit": data_limit}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def search_users(self, q: Optional[str] = None) -> Any:
        """Search Users
        
        Args:
            q (str): Search query.
        """
        _path = f"/search/users"
        _params = {}
        _data = {"q": q}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def search_profile_posts(self, q: Optional[str] = None, user_id: Optional[int] = None, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Search Profile Posts
        
        Args:
            q (str): Search query. Can be skipped if **user_id** is set.
            user_id (int): User ID to filter profile posts.
            page (int): Page number of results.
            limit (int): Number of results in a page.
        """
        _path = f"/search/profile-posts"
        _params = {}
        _data = {"q": q, "user_id": user_id, "page": page, "limit": limit}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def search_tagged(self, tag: Optional[str] = None, tags: Optional[List[str]] = None, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Search Tagged
        
        Args:
            tag (str): Tag to search for tagged contents.
            tags (List[str]): Array of tags to search for tagged contents.
            page (int): Page number of results.
            limit (int): Number of results in a page.
        """
        _path = f"/search/tagged"
        _params = {}
        _data = {"tag": tag, "tags": tags, "page": page, "limit": limit}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def search_results(self, search_id: Any, page: Optional[int] = None, limit: Optional[int] = None) -> Any:
        """Get Search Results
        
        Args:
            search_id (Any): Search ID.
            page (int): Page number of results.
            limit (int): Number of results in a page.
        """
        _path = f"/search/{search_id}/results"
        _params = {}
        _data = {"page": page, "limit": limit}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("GET", _path, params=_params, json=_data)

    def batch_execute(self) -> Any:
        """Batch
        """
        _path = f"/batch"
        _params = {}
        _data = {}
        return self._request("POST", _path, params=_params, json=_data)

    def chatbox_index(self, room_id: Optional[RoomIDModel] = None) -> Any:
        """Get Chats
        
        Args:
            room_id (RoomIDModel): Room id.
        """
        _path = f"/chatbox"
        _params = {"room_id": room_id}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def chatbox_get_messages(self, room_id: RoomIDModel, before_message_id: Optional[int] = None) -> Any:
        """Get Chat Messages
        
        Args:
            room_id (RoomIDModel): Room id.
            before_message_id (int): Message id to get older chat messages.
        """
        _path = f"/chatbox/messages"
        _params = {"room_id": room_id, "before_message_id": before_message_id}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def chatbox_post_message(self, room_id: RoomIDModel, message: str, reply_message_id: Optional[int] = None) -> Any:
        """Create Chat Message
        
        Args:
            room_id (RoomIDModel): 
            reply_message_id (int): ID of the message being replied to.
            message (str): Content of the chat message.
        """
        _path = f"/chatbox/messages"
        _params = {}
        _data = {"room_id": room_id, "message": message, "reply_message_id": reply_message_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def chatbox_edit_message(self, message_id: int, message: str) -> Any:
        """Edit Chat Message
        
        Args:
            message_id (int): Message id.
            message (str): New content of the chat message.
        """
        _path = f"/chatbox/messages"
        _params = {}
        _data = {"message_id": message_id, "message": message}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("PUT", _path, params=_params, json=_data)

    def chatbox_delete_message(self, message_id: int) -> Any:
        """Delete Chat Message
        
        Args:
            message_id (int): Message id.
        """
        _path = f"/chatbox/messages"
        _params = {}
        _data = {"message_id": message_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("DELETE", _path, params=_params, json=_data)

    def chatbox_online(self, room_id: RoomIDModel) -> Any:
        """Get Chat Online
        
        Args:
            room_id (RoomIDModel): Room id.
        """
        _path = f"/chatbox/messages/online"
        _params = {"room_id": room_id}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def chatbox_report_reasons(self, message_id: int) -> Any:
        """Get Chat Message Report Reasons
        
        Args:
            message_id (int): Message id.
        """
        _path = f"/chatbox/messages/report"
        _params = {"message_id": message_id}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def chatbox_report(self, message_id: int, reason: str) -> Any:
        """Report Chat Message
        
        Args:
            message_id (int): Message id.
            reason (str): Report reason.
        """
        _path = f"/chatbox/messages/report"
        _params = {}
        _data = {"message_id": message_id, "reason": reason}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def chatbox_get_leaderboard(self, duration: Optional[str] = None) -> Any:
        """Get Chat Leaderboard
        
        Args:
            duration (str): Duration.
        """
        _path = f"/chatbox/messages/leaderboard"
        _params = {"duration": duration}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def chatbox_get_ignore(self) -> Any:
        """Get Ignored Chat Users
        """
        _path = f"/chatbox/ignore"
        _params = {}
        return self._request("GET", _path, params=_params)

    def chatbox_post_ignore(self, user_id: UserIDModel) -> Any:
        """Ignore Chat User
        
        Args:
            user_id (UserIDModel): 
        """
        _path = f"/chatbox/ignore"
        _params = {}
        _data = {"user_id": user_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("POST", _path, params=_params, json=_data)

    def chatbox_delete_ignore(self, user_id: UserIDModel) -> Any:
        """Unignore Chat User
        
        Args:
            user_id (UserIDModel): 
        """
        _path = f"/chatbox/ignore"
        _params = {}
        _data = {"user_id": user_id}
        _data = {k: v for k, v in _data.items() if v is not None}
        return self._request("DELETE", _path, params=_params, json=_data)

    def forms_list(self, page: Optional[int] = None) -> Any:
        """Get Forms List
        
        Args:
            page (int): Page number of forms.
        """
        _path = f"/forms"
        _params = {"page": page}
        _params = {k: v for k, v in _params.items() if v is not None}
        return self._request("GET", _path, params=_params)

    def forms_create(self) -> Any:
        """Create Form
        """
        _path = f"/forms/save"
        _params = {}
        _data = {}
        return self._request("POST", _path, params=_params, json=_data)
